id: P561AF619
initial_creation_type: input
source_metadata:
  title: Kachöpa Series
  language: es
  description: Prayers and Practices
  volume:
    589d15ef45614648ab5ce39a707b4695:
      title: Raising the Windhorse
      parent: Prayers and Practices
created_at: '2022-03-01T00:09:28.226127'
last_modified_at: '2022-03-01T00:09:28.226130'
